import{a as x,S as w,i as c}from"./assets/vendor-D1eTGYtO.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();async function h(t,a){const o="https://pixabay.com/api/",i="45377125-53da1a565bd8b37af868a9bcd";try{return(await x.get(o,{params:{key:i,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15}})).data}catch{}}const u=document.querySelector(".gallery-container"),m=document.querySelector(".loader"),l=document.querySelector(".load-more-btn"),S=new w(".gallery-container a",{captions:!0,captionsData:"alt",captionDelay:250});function f(t){const a=t.map(({webformatURL:o,largeImageURL:i,tags:e,likes:r,views:n,comments:q,downloads:P})=>`
        <li class="gallery-item">
        <a href="${i}">
          <img src="${o}" alt="${e}" />
          <div class="statictics">
            <div class = "statictics-text"><h3>Likes</h3><p> ${r}</p></div>
            <div class = "statictics-text"><h3>Views</h3><p>${n}</p></div>
            <div class = "statictics-text"><h3>Comments</h3><p>${q}</p></div>
            <div class = "statictics-text"><h3>Downloads</h3><p>${P}</p></div>
          </div>
        </a></li>`).join("");y(),u.insertAdjacentHTML("beforeend",a),S.refresh()}function B(){const t="";u.innerHTML=t,p()}function g(){m.classList.remove("hidden")}function y(){m.classList.add("hidden")}function E(){l.classList.remove("hidden")}function p(){l.classList.add("hidden")}function v(){l.disabled=!1}function M(){l.disabled=!0}function $(){const t=u.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}const d=document.querySelector(".form"),L=document.querySelector(".load-more-btn"),s={page:1,maxPage:0,q:"",perPage:15};d.addEventListener("submit",O);async function O(t){if(t.preventDefault(),B(),s.q=t.currentTarget.elements.input.value.trim(),s.q===""){c.error({message:"Please enter your search query.",position:"topRight"}),d.reset();return}g(),s.page=1;try{const{hits:a,totalHits:o}=await h(s.q,s.page);s.maxPage=Math.ceil(o/s.perPage),f(a),s.maxPage>1?(E(),v(),L.addEventListener("click",b)):p(),a.length===0&&c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}catch(a){c.error({title:"Error",message:a.message})}finally{d.reset()}}async function b(){M(),g(),s.page+=1;try{const{hits:t}=await h(s.q,s.page);f(t),$()}catch(t){c.error({title:"Error",message:t.message})}finally{y(),s.page===s.maxPage?(L.removeEventListener("click",b),p(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}}
//# sourceMappingURL=commonHelpers.js.map
