import{a as P,S as x,i as c}from"./assets/vendor-D1eTGYtO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function p(t,o){const s="https://pixabay.com/api/",i="45377125-53da1a565bd8b37af868a9bcd";try{return(await P.get(s,{params:{key:i,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}catch{}}const u=document.querySelector(".gallery-container"),h=document.querySelector(".loader"),l=document.querySelector(".load-more-btn"),w=new x(".gallery-container a",{captions:!0,captionsData:"alt",captionDelay:250});function m(t){const o=t.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:n,comments:b,downloads:q})=>`
        <li class="gallery-item">
        <a href="${i}">
          <img src="${s}" alt="${e}" />
          <div class="statictics">
            <div class = "statictics-text"><h3>Likes</h3><p> ${r}</p></div>
            <div class = "statictics-text"><h3>Views</h3><p>${n}</p></div>
            <div class = "statictics-text"><h3>Comments</h3><p>${b}</p></div>
            <div class = "statictics-text"><h3>Downloads</h3><p>${q}</p></div>
          </div>
        </a></li>`).join("");g(),u.insertAdjacentHTML("beforeend",o),w.refresh()}function S(){const t="";u.innerHTML=t}function f(){h.classList.remove("hidden")}function g(){h.classList.add("hidden")}function B(){l.classList.remove("hidden")}function E(){l.classList.add("hidden")}function y(){l.disabled=!1}function M(){l.disabled=!0}function $(){const t=u.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}const d=document.querySelector(".form"),v=document.querySelector(".load-more-btn"),a={page:1,maxPage:0,q:"",perPage:15};d.addEventListener("submit",O);async function O(t){if(t.preventDefault(),S(),a.q=t.currentTarget.elements.input.value.trim(),a.q===""){c.error({message:"Please enter your search query.",position:"topRight"}),d.reset();return}f(),a.page=1;try{const{hits:o,totalHits:s}=await p(a.q,a.page);a.maxPage=Math.ceil(s/a.perPage),m(o),a.maxPage>1&&(B(),y(),v.addEventListener("click",L)),o.length===0&&c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}catch(o){c.error({title:"Error",message:o.message})}finally{d.reset()}}async function L(){M(),f(),a.page+=1;try{const{hits:t}=await p(a.q,a.page);m(t),$()}catch(t){c.error({title:"Error",message:t.message})}finally{g(),a.page===a.maxPage?(v.removeEventListener("click",L),E(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):y()}}
//# sourceMappingURL=commonHelpers.js.map
